version: '2'
services:
  mongo:
    image: mongo:3.2-jessie
    ports:
      - "27017:27017"
    container_name : movie-app
    network_mode : host
   
  spring:
    build: moviesdb/
    restart: always
    container_name: spring-docker
    depends_on:
      - mongo
    ports:
      - "8099:8080"
    expose:
      - 8099





